linux:
  hosts:
  children:
    rocky:
      hosts:
        10.0.5.77:
          hostname: Rocky-1
          lan_ip: 10.0.5.10
        10.0.5.76:
          hostname: Rocky-2
          lan_ip: 10.0.5.11
        10.0.5.75:
          hostname: Rocky-3
          lan_ip: 10.0.5.12
      vars:
        device: ens34
    ubuntu:
      hosts:
        10.0.5.78:
          hostname: ubuntu-1
          lan_ip: 10.0.5.30
        10.0.5.79:
          hostname: ubuntu-2
          lan_ip: 10.0.5.31
      vars:
        device: ens34

  vars:
    public_key: "ssh-rsa XePX/5v1K+bzsvnPtvX4M2hKXt0XR83PA6lTAFASFPlXXXASF= admin@xubuntu-wan"
    ansible_user: rangeuser
    prefix: 24
    gateway: 10.0.5.2
    name_server: 10.0.5.5
    domain: blue17.local
